// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <AppKit/AppKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreServices/CoreServices.h>

@interface AppDelegate: NSObject <NSApplicationDelegate>
-(IBAction) applicationDidFinishLaunching:(id) notification;

@end

